
version: "3.0"
services:
  web:
    container_name: heritage-app
    env_file:
      - .env
    build: .
    ports:
      - 5050:${SERVER_PORT}/tcp
    links:
      - mysql
  mysql:
    container_name: heritage-db
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    image: library/mysql:8.0.21
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}/tcp